In [42]:
import pandas as pd
import numpy as np
from copy import deepcopy

# SEED = np.random.randint(100)
np.random.seed(53)

In [327]:
animals = pd.read_csv('CA2Data/animals', header=None, delimiter=' ')
countries = pd.read_csv('CA2Data/countries', header=None, delimiter=' ')
fruits = pd.read_csv('CA2Data/fruits', header=None, delimiter=' ')
veggies = pd.read_csv('CA2Data/veggies', header=None, delimiter=' ')
# Assign numerical 'category' values corresponding to true labels
animals[0] = 0
countries[0] = 1
fruits[0] = 2
veggies[0] = 3

dataset = pd.concat([animals, countries, fruits, veggies], ignore_index=True)
# dataset

In [328]:
# store category data to compute metrics
category = np.array(dataset[0])
# category = np.array(dataset[0]).reshape(-1,1)
category.shape

(327,)

In [329]:
# drop category column
dataset.drop(columns=[0], inplace=True)
# dataset

In [330]:
data = np.array(dataset)
data.shape

(327, 300)

In [261]:
# K-mean * K-medians

def euclidean_distance(X,Y):
    # Return the Euclidean distance between X and Y
    # return np.sqrt(np.sum((X-Y)**2))
    return np.linalg.norm(X-Y)


def manhattan_distance(X,Y):
    # Return the Manhattan distance between X and Y
    # return np.abs(X-Y).sum()
    return np.sum(np.abs(X-Y))


def check_convergence(k_means, k_medians):
    # if k_means:
    #     np.sum()
    pass


def group_data_to_cluster(num_centroids):
    # Initialise 'clusters', to later store the centroid index value to the corresponding datapoint index
    clusters = np.zeros((len(dataset), 1))
    num_datapoints = len(dataset)

    # loop through each datapoint
    for index in range(num_datapoints):
        # Initialise 'distances', to store the 'distance' value from each centroid to the datapoint
        distances = np.zeros((num_centroids, 1))
        # Loop through each centroid
        for centroid_index in range(num_centroids):
            if k_means:
                # for k-means, find the eucledian distance from the datapoint to each centroid
                distance_to_centroid = euclidean_distance(dataset[index], centroids[centroid_index])
                # update the 'distance' value to the 'distances' array
                distances[centroid_index] = distance_to_centroid

            elif k_medians:
                # for k-medians, find the manhattan distance from the datapoint to each centroid
                distance_to_centroid = manhattan_distance(dataset[index], centroids[centroid_index])
                # update the 'distance' value to the 'distances' array
                distances[centroid_index] = distance_to_centroid

        # Get the closest centroids index value
        closest_centroid_index = np.argmin(distances)
        # Assign the closest centroid index value to the corresponding datapoint index (in the 'clusters' array)
        clusters[index] = closest_centroid_index
#     print(clusters)
    return clusters


def update_centroids(clusters, num_centroids):
    # Iterate over the centroids, to update them based on the updated cluster data
    for centroid_index in range(num_centroids):
        if k_means:
            # Compute the mean of datapoints for each cluster, and set them as the new centroids
            centroids[centroid_index] = np.mean(data[clusters.flatten() == centroid_index], axis=0)
        elif k_medians:
            # Compute the median of datapoints for each cluster, and set them as the new centroids
            centroids[centroid_index] = np.median(data[clusters.flatten() == centroid_index], axis=0)
    return centroids


def compute_metrics(k):
    num_datapoints = len(data)
    print(num_datapoints)
    precision = np.zeros((num_datapoints))
    recall = np.zeros((num_datapoints))
    f_score = np.zeros((num_datapoints))
    for index in range(num_datapoints):
        # get the count of the 'category' from it's assigned 'cluster'
        category_in_cluster_count = np.count_nonzero(cat[clust==clust[index]] == cat[index])
        # get the total count of datapoints belonging to the 'category' in the dataset
        category_total_count = np.count_nonzero(cat==cat[index])
        # get the count of datapoints assigned to the 'cluster'
        cluster_elements_count = np.count_nonzero(clust == clust[index])
    #     count = np.sum(cat[clust==clust[index]]==cat[index])
        # compute precision
        precision[index] = category_in_cluster_count / cluster_elements_count
        recall[index] = category_in_cluster_count / category_total_count
    #     f_score[index] = 2*precision[index]*recall[index]/(precision[index]+recall[index])
    #     print(f'Count of category {cat[index]} in cluster {clust[index]} = {category_in_cluster_count}')
    #     print(f'Count of category {cat[index]} in dataset = {category_total_count}')
    #     print(f'Total elements in cluster {clust[index]} = {cluster_elements_count}')
    f_score = 2*precision*recall/(precision+recall)
    print(precision)
    print(recall)
    print(f_score)
    precision = np.sum(precision)/num_datapoints
    recall = np.sum(recall)/num_datapoints
    f_score = np.sum(f_score)/num_datapoints
    print(precision)
    print(recall)
    print(f_score)
    return precision, recall, f_score


In [262]:
import pandas as pd
import numpy as np
from copy import deepcopy

SEED = np.random.randint(100)
np.random.seed(53)
# print(SEED)
# 53, 40, 18

# import data
data1 = pd.read_csv('CA2Data/animals', header=None, delimiter=' ')
data2 = pd.read_csv('CA2Data/countries', header=None, delimiter=' ')
data3 = pd.read_csv('CA2Data/fruits', header=None, delimiter=' ')
data4 = pd.read_csv('CA2Data/veggies', header=None, delimiter=' ')
# dataset = pd.concat([data1, data2, data3, data4])

# concatenate data points
dataset = pd.concat([data1.iloc[:,1:], data2.iloc[:,1:], data3.iloc[:,1:], data4.iloc[:,1:]])

# convert data set to numpy array
dataset = np.array(dataset)

# choose 'k' for number of clusters 
k=4
num_centroids = k

# Initialise 'k' centroids (y1, .. yk) randomly from the data set
centroids = dataset[np.random.randint(dataset.shape[0], size=num_centroids), :]
print('Initial centroids\n', centroids)


# To only run K_means
k_means = True
k_medians = False

# To only run K_medians
# k_means = False
# k_medians = True

data = deepcopy(dataset)

#### update centroids based on new cluster data

for _ in range(100):
    # if check_convergence():
    #     break
    num_centroids = k

    # for the current iteration, get the centroids (index value) assigned to the corresponding datapoints index
    clusters = group_data_to_cluster(num_centroids)
    centroids = update_centroids(clusters, num_centroids)

precision, recall, f_score = compute_metrics(num_centroids)
print(precision)
print("\nKMeans Centroids from computed for k = 4:")
print(centroids)

Initial centroids
 [[ 0.52242  -0.14079  -0.096228 ... -0.43478   0.86687   0.045675]
 [-0.15919   0.13402  -0.60023  ... -0.51513  -0.31658   0.25369 ]
 [ 0.12423  -0.063348  0.25331  ... -0.7498   -0.073445 -0.011316]
 [ 0.44003   0.41338  -0.3769   ...  0.16981   0.022406  0.48342 ]]
327


IndexError: index 10 is out of bounds for axis 0 with size 10

In [30]:
#### ******************* IGNORE CODE BELOW ********************

#### TESTING THE CODE

from sklearn.cluster import KMeans

model = KMeans(n_clusters=k)
model.fit(data)
print("\n\nOutput from SKLEARN")
print(model.cluster_centers_)



Output from SKLEARN
[[-0.23340746 -0.0955901   0.07988927 ... -0.43806341 -0.06295059
   0.05672025]
 [ 0.38627178  0.3143458   0.05909229 ...  0.09175967  0.11883498
   0.25313992]
 [-0.10709906 -0.10474646 -0.06334103 ... -0.08248652 -0.23759206
   0.13968116]
 [-0.07048999 -0.20060509 -0.26966388 ... -0.1941668   0.06881185
   0.18472587]]


In [18]:
d = np.array([[1,2,3], 
              [2.3,5.2,6],
              [9,11,7]])
print(d)
np.median(d, axis=0)

[[ 1.   2.   3. ]
 [ 2.3  5.2  6. ]
 [ 9.  11.   7. ]]


array([2.3, 5.2, 6. ])

In [195]:
cat = np.array((1,2,3,1,3,2,2,3,2,3))
print(cat)

clust   = np.array((5,6,5,4,5,6,5,5,4,7))
print(clust)

[1 2 3 1 3 2 2 3 2 3]
[5 6 5 4 5 6 5 5 4 7]


In [110]:
comb = np.vstack((cat, clust))
print(comb.shape)
comb

(2, 10)


array([[1, 2, 3, 1, 3, 2, 2, 3, 2, 3],
       [5, 6, 5, 4, 5, 6, 5, 5, 4, 7]])

In [197]:
np.count_nonzero(comb==2, axis=1)

array([4, 0])

In [198]:
np.bincount(cat)

array([0, 2, 4, 4])

In [213]:
mask = cat[clust==5]
np.count_nonzero(mask[mask==2])
np.count_nonzero(mask==2)

print(mask)
print(mask==2)
print(mask[mask==2])

np.count_nonzero(cat[clust==5]==2)

[1 3 3 2 3]
[False False False  True False]
[2]


1

In [253]:
len_data = len(clust)
precision = np.zeros((len_data))
recall = np.zeros((len_data))
f_score = np.zeros((len_data))
for i in range(len_data):
    # get the count of the 'category' from it's assigned 'cluster'
    category_in_cluster_count = np.count_nonzero(cat[clust == clust[i]] == cat[i])
    # get the total count of datapoints belonging to the 'category' in the dataset
    category_total_count = np.count_nonzero(cat==cat[i])
    # get the count of datapoints assigned to the 'cluster'
    cluster_elements_count = np.count_nonzero(clust == clust[i])
#     count = np.sum(cat[clust==clust[i]]==cat[i])
    # compute precision
    precision[i] = category_in_cluster_count / cluster_elements_count
    recall[i] = category_in_cluster_count / category_total_count
#     f_score[i] = 2*precision[i]*recall[i]/(precision[i]+recall[i])
#     print(f'Count of category {cat[i]} in cluster {clust[i]} = {category_in_cluster_count}')
#     print(f'Count of category {cat[i]} in dataset = {category_total_count}')
#     print(f'Total elements in cluster {clust[i]} = {cluster_elements_count}')
f_score = 2*precision*recall/(precision+recall)
print(precision)
print(recall)
print(f_score)
print(np.sum(precision)/len_data)
print(np.sum(recall)/len_data)
print(np.sum(f_score)/len_data)

[0.2 1.  0.6 0.5 0.6 1.  0.2 0.6 0.5 1. ]
[0.5  0.5  0.75 0.5  0.75 0.5  0.25 0.75 0.25 0.25]
[0.28571429 0.66666667 0.66666667 0.5        0.66666667 0.66666667
 0.22222222 0.66666667 0.33333333 0.4       ]
0.62
0.5
0.5074603174603174


In [276]:
print(cat)
print(clust)

[1 2 3 1 3 2 2 3 2 3]
[5 6 5 4 5 6 5 5 4 7]


In [257]:
for i in range(10):
    mask = cat[clust==clust[i]]
#     count = np.count_nonzero(mask==cat[i])
    count = np.count_nonzero((cat[clust==clust[i]]) == cat[i])
    print(f'Count of category {cat[i]} in cluster {clust[i]} = {count}')
# mask

Count of category 1 in cluster 5 = 1
Count of category 2 in cluster 6 = 2
Count of category 3 in cluster 5 = 3
Count of category 1 in cluster 4 = 1
Count of category 3 in cluster 5 = 3
Count of category 2 in cluster 6 = 2
Count of category 2 in cluster 5 = 1
Count of category 3 in cluster 5 = 3
Count of category 2 in cluster 4 = 1
Count of category 3 in cluster 7 = 1


In [203]:
cat[clust==5][cat==2]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 10

In [206]:
comb[(comb==5) | (comb==3)]

array([3, 3, 3, 3, 5, 5, 5, 5, 5])

In [ ]:
# # select only classes needed for classification
# data = data[np.where((data[:,-1] == positive_class) | (data[:,-1] == negative_class))]

# # converting class labels to numeric values [+1 or -1] based on the 1 v/s rest approach
# data[data=='class-1'] = 1
# data[(data=='class-2') | (data=='class-3')] = -1

In [229]:
np.count_nonzero(np.array((0,0,1))==0)

2